   
options:
  logging: CLOUD_LOGGING_ONLY

timeout: "60m"

steps:
- name: hashicorp/terraform:1.6
  dir: gcp-devops/infra
  entrypoint: terraform
  args: ["init"]

- name: hashicorp/terraform:1.6
  dir: gcp-devops/infra
  entrypoint: terraform
  args: ["validate"]

- name: hashicorp/terraform:1.6
  dir: gcp-devops/infra
  entrypoint: terraform
  args: ["plan", "-out=tfplan"]

- name: hashicorp/terraform:1.6
  dir: gcp-devops/infra
  entrypoint: terraform
  args: ["apply", "tfplan"]
